
name: CI/CD

on:
  push:
    branches: [ "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build ./SickLeaveTelegramBot.App --file Dockerfile --tag tg-bot:latest
      - name: Save image
        run: docker save tg-bot:latest -o docker-image.tar
      - name: install sshpass
        run: apt-get install sshpass
      - name: stop and remove old container
        run: sshpass -p ${{ secrets.Password }} ssh -o "StrictHostKeyChecking=no" ${{ secrets.Host }} "cd /home/max/tg-bot; ${{ secrets.Password }} | sudo -S docker stop tg-bot:latest; rm docker-image.tar" || true
      - name: upload docker image
        run: sshpass -p ${{ secrets.Password }} scp docker-image.tar ${{ secrets.Host }}:/home/max/tg-bot/docker-image.tar
      - name: load image and start
        run: sshpass -p ${{ secrets.Password }} ssh ${{ secrets.Host }} "cd /home/max/tg-bot && echo ${{ secrets.Password }} | sudo -S docker load -i docker-image.tar && echo ${{ secrets.Password }} | sudo -S sudo docker run -e "BotConfiguration__BotToken=${{ secrets.BOTCONFIGURATION__BOTTOKEN }}" tg-bot"